// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy0HT6QJeMd5rt91p4Yxs0vi8UxEavc38',
    appId: '1:877293697792:web:d4ec1f793b9ab3676a51e5',
    messagingSenderId: '877293697792',
    projectId: 'see-gas',
    authDomain: 'see-gas.firebaseapp.com',
    storageBucket: 'see-gas.appspot.com',
    measurementId: 'G-9WSZ8RFTWE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArnoq9DzW7MWVhF7vUW9WxRvIL2aEF_40',
    appId: '1:877293697792:android:bfa877c352e5aa5f6a51e5',
    messagingSenderId: '877293697792',
    projectId: 'see-gas',
    storageBucket: 'see-gas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvyodFIJDzDwmSqCZStp_qNPvHIvcMRE8',
    appId: '1:877293697792:ios:91ab85d8318714866a51e5',
    messagingSenderId: '877293697792',
    projectId: 'see-gas',
    storageBucket: 'see-gas.appspot.com',
    iosClientId: '877293697792-js2t18k5nhr39dujv86fa53u2ihgguil.apps.googleusercontent.com',
    iosBundleId: 'com.example.seeGasApp',
  );
}
